name: toon_x_json
description: TOON <--> JSON, TOON- A compact JSON format
version: 0.0.3
repository: https://github.com/Tushargupta9800/toon-dart
documentation: https://github.com/Tushargupta9800/toon-dart#readme
issue_tracker: https://github.com/Tushargupta9800/toon-dart/issues

environment:
  sdk: ^3.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
